package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EducationinfoId generated by hbm2java
 */
@Embeddable
public class EducationinfoId implements java.io.Serializable {

	private int userId;
	private Integer schoolId;
	private Integer programId;
	private Date startDate;
	private Date endDate;

	public EducationinfoId() {
	}

	public EducationinfoId(int userId) {
		this.userId = userId;
	}

	public EducationinfoId(int userId, Integer schoolId, Integer programId, Date startDate, Date endDate) {
		this.userId = userId;
		this.schoolId = schoolId;
		this.programId = programId;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "schoolID")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "programID")
	public Integer getProgramId() {
		return this.programId;
	}

	public void setProgramId(Integer programId) {
		this.programId = programId;
	}

	@Column(name = "startDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "endDate", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EducationinfoId))
			return false;
		EducationinfoId castOther = (EducationinfoId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getSchoolId() == castOther.getSchoolId()) || (this.getSchoolId() != null
						&& castOther.getSchoolId() != null && this.getSchoolId().equals(castOther.getSchoolId())))
				&& ((this.getProgramId() == castOther.getProgramId()) || (this.getProgramId() != null
						&& castOther.getProgramId() != null && this.getProgramId().equals(castOther.getProgramId())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this.getStartDate() != null
						&& castOther.getStartDate() != null && this.getStartDate().equals(castOther.getStartDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this.getEndDate() != null
						&& castOther.getEndDate() != null && this.getEndDate().equals(castOther.getEndDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getSchoolId() == null ? 0 : this.getSchoolId().hashCode());
		result = 37 * result + (getProgramId() == null ? 0 : this.getProgramId().hashCode());
		result = 37 * result + (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37 * result + (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		return result;
	}

}
