package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Personalinfo generated by hbm2java
 */
@Entity
@Table(name = "personalinfo", catalog = "socialnetwork_version2")
public class Personalinfo implements java.io.Serializable {

	private PersonalinfoId id;
	private Users users;

	public Personalinfo() {
	}

	public Personalinfo(PersonalinfoId id, Users users) {
		this.id = id;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "userID", nullable = false)),
			@AttributeOverride(name = "gender", column = @Column(name = "gender", length = 6)),
			@AttributeOverride(name = "dateOfBirth", column = @Column(name = "dateOfBirth", length = 10)),
			@AttributeOverride(name = "phoneNumber", column = @Column(name = "phoneNumber", length = 15)),
			@AttributeOverride(name = "personalEmail", column = @Column(name = "personalEmail", length = 64)),
			@AttributeOverride(name = "workEmail", column = @Column(name = "workEmail", length = 64)),
			@AttributeOverride(name = "bio", column = @Column(name = "bio", length = 65535)) })
	public PersonalinfoId getId() {
		return this.id;
	}

	public void setId(PersonalinfoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
