package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Photos generated by hbm2java
 */
@Entity
@Table(name = "photos", catalog = "socialnetwork_version2")
public class Photos implements java.io.Serializable {

	private Integer photoId;
	private String url;
	private String caption;
	private Date dateOfUpload;
	private Set<Userphotos> userphotoses = new HashSet<Userphotos>(0);

	public Photos() {
	}

	public Photos(Date dateOfUpload) {
		this.dateOfUpload = dateOfUpload;
	}

	public Photos(String url, String caption, Date dateOfUpload, Set<Userphotos> userphotoses) {
		this.url = url;
		this.caption = caption;
		this.dateOfUpload = dateOfUpload;
		this.userphotoses = userphotoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "photoID", unique = true, nullable = false)
	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "caption", length = 200)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateOfUpload", nullable = false, length = 19)
	public Date getDateOfUpload() {
		return this.dateOfUpload;
	}

	public void setDateOfUpload(Date dateOfUpload) {
		this.dateOfUpload = dateOfUpload;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "photos")
	public Set<Userphotos> getUserphotoses() {
		return this.userphotoses;
	}

	public void setUserphotoses(Set<Userphotos> userphotoses) {
		this.userphotoses = userphotoses;
	}

}
