package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelationshipsId generated by hbm2java
 */
@Embeddable
public class RelationshipsId implements java.io.Serializable {

	private int userId;
	private Integer userId2;
	private String status;

	public RelationshipsId() {
	}

	public RelationshipsId(int userId) {
		this.userId = userId;
	}

	public RelationshipsId(int userId, Integer userId2, String status) {
		this.userId = userId;
		this.userId2 = userId2;
		this.status = status;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "userID2")
	public Integer getUserId2() {
		return this.userId2;
	}

	public void setUserId2(Integer userId2) {
		this.userId2 = userId2;
	}

	@Column(name = "status", length = 17)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelationshipsId))
			return false;
		RelationshipsId castOther = (RelationshipsId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getUserId2() == castOther.getUserId2()) || (this.getUserId2() != null
						&& castOther.getUserId2() != null && this.getUserId2().equals(castOther.getUserId2())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getUserId2() == null ? 0 : this.getUserId2().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
