package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Relationships generated by hbm2java
 */
@Entity
@Table(name = "relationships", catalog = "socialnetwork_version2")
public class Relationships implements java.io.Serializable {

	private RelationshipsId id;
	private Users users;

	public Relationships() {
	}

	public Relationships(RelationshipsId id, Users users) {
		this.id = id;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "userID", nullable = false)),
			@AttributeOverride(name = "userId2", column = @Column(name = "userID2")),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 17)) })
	public RelationshipsId getId() {
		return this.id;
	}

	public void setId(RelationshipsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
