package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Schoolprograms generated by hbm2java
 */
@Entity
@Table(name = "schoolprograms", catalog = "socialnetwork_version2")
public class Schoolprograms implements java.io.Serializable {

	private Integer programId;
	private String programName;
	private Set<Educationinfo> educationinfos = new HashSet<Educationinfo>(0);

	public Schoolprograms() {
	}

	public Schoolprograms(String programName, Set<Educationinfo> educationinfos) {
		this.programName = programName;
		this.educationinfos = educationinfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "programID", unique = true, nullable = false)
	public Integer getProgramId() {
		return this.programId;
	}

	public void setProgramId(Integer programId) {
		this.programId = programId;
	}

	@Column(name = "programName", length = 100)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schoolprograms")
	public Set<Educationinfo> getEducationinfos() {
		return this.educationinfos;
	}

	public void setEducationinfos(Set<Educationinfo> educationinfos) {
		this.educationinfos = educationinfos;
	}

}
