package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Schools generated by hbm2java
 */
@Entity
@Table(name = "schools", catalog = "socialnetwork_version2")
public class Schools implements java.io.Serializable {

	private Integer schoolId;
	private String schoolName;
	private Set<Educationinfo> educationinfos = new HashSet<Educationinfo>(0);

	public Schools() {
	}

	public Schools(String schoolName, Set<Educationinfo> educationinfos) {
		this.schoolName = schoolName;
		this.educationinfos = educationinfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schoolID", unique = true, nullable = false)
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "schoolName", length = 100)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schools")
	public Set<Educationinfo> getEducationinfos() {
		return this.educationinfos;
	}

	public void setEducationinfos(Set<Educationinfo> educationinfos) {
		this.educationinfos = educationinfos;
	}

}
