package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UservideosId generated by hbm2java
 */
@Embeddable
public class UservideosId implements java.io.Serializable {

	private int userId;
	private int videoId;

	public UservideosId() {
	}

	public UservideosId(int userId, int videoId) {
		this.userId = userId;
		this.videoId = videoId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "videoID", nullable = false)
	public int getVideoId() {
		return this.videoId;
	}

	public void setVideoId(int videoId) {
		this.videoId = videoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UservideosId))
			return false;
		UservideosId castOther = (UservideosId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getVideoId() == castOther.getVideoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getVideoId();
		return result;
	}

}
