package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userphotos generated by hbm2java
 */
@Entity
@Table(name = "userphotos", catalog = "socialnetwork_version2")
public class Userphotos implements java.io.Serializable {

	private UserphotosId id;
	private Photos photos;
	private Users users;

	public Userphotos() {
	}

	public Userphotos(UserphotosId id, Photos photos, Users users) {
		this.id = id;
		this.photos = photos;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "userID", nullable = false)),
			@AttributeOverride(name = "photoId", column = @Column(name = "photoID", nullable = false)) })
	public UserphotosId getId() {
		return this.id;
	}

	public void setId(UserphotosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "photoID", nullable = false, insertable = false, updatable = false)
	public Photos getPhotos() {
		return this.photos;
	}

	public void setPhotos(Photos photos) {
		this.photos = photos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
