package persistence;// default package
// Generated 17 mars 2017 11:03:08 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserphotosId generated by hbm2java
 */
@Embeddable
public class UserphotosId implements java.io.Serializable {

	private int userId;
	private int photoId;

	public UserphotosId() {
	}

	public UserphotosId(int userId, int photoId) {
		this.userId = userId;
		this.photoId = photoId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "photoID", nullable = false)
	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(int photoId) {
		this.photoId = photoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserphotosId))
			return false;
		UserphotosId castOther = (UserphotosId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getPhotoId() == castOther.getPhotoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getPhotoId();
		return result;
	}

}
